### ISSUE TITLE
Rotate player on move

### ISSUE THREAD

**Issue by Sharkules** [JadenCooper/BogBuddiesToilets#57]
Player capsule currently doesn't face the correct direction on moving

**Comment by SB-Lamia** [comment]
This is already implemented. Its a float variable that is attached to each of the arrow game objects. Screenshot below.
![image](https://user-images.githubusercontent.com/78123942/227821564-9dfe4492-c067-458c-9808-1a2c13db869b.png)
You just change the rotation to whatever the direction you want between 0 and 360.
