### ISSUE TITLE
Have arrows face player

### ISSUE THREAD

**Issue by Sharkules** [JadenCooper/BogBuddiesToilets#61]
Sometimes they are inside out/mirrored

**Comment by JadenCooper** [comment]
I Think Alision Meant Have The Text On The Arrows Face The Players Rather Than The Arrows, Could Probably Do The Same Thing With The Text Displays If We Wanted?

**Comment by Sharkules** [comment]
Arrows face target direction - text faces player. Incorrect issue name. Issue completed. :)
