### ISSUE TITLE
Branching off the project into 2 repositories

### ISSUE THREAD

**Issue by SB-Lamia** [JadenCooper/BogBuddiesToilets#96]
Adon has talked about branching off the respository into 2. making it so we have a branch that is able for our client to meet their needs. and a 2nd branch that will be more of a implementation branch for new features that the client is unsure about. I want some opinions on how this should be done?

Should we make 2 staging branchs and 2 main branches? one for each option. and have 2 project boards? or keep the same project board but split features into working on for client and not working on for client. Since what adon described sounded like it would be very different to the main thing our client wants.

**Comment by Sharkules** [comment]
Did he say two repos, or can we just have two main branches?

**Comment by SB-Lamia** [comment]
Yeah mybad I meant branches instead of respository. Same repo but just adding more branches

**Comment by JadenCooper** [comment]
I Think Two Project Boards Will Make Everything Clearer. Probably Add Two labels Too For The Issues. One For Client One For The Game. Creating Two Main Branches Should Be Sufficient Too.
